 export const constants = {

    LOGIN:'Login',
    NOT_LOGGED_IN :'you are not logged in',
    OK : 'ok',
    CANCEL :'cancel',
    OOPS :'Oops!',
    FILL_FORM : 'Please fill the form correctly',
    EMAIL : 'Email Address',
    PASSWORD: 'Password',
    INVALID_EMAIL:'Invalid Email Id',
    REQUIRED_PASSWORD:'Password is Required',
    WELCOME :'welcome',
    ADMIN : 'Admin',
    LOGOUT:'Logout',
    HOME:'Home',
    ISBN :'Enter the isbn of the book:',
    TITLE :'Enter the Title of the book:',
    REALEASE_YEAR:'Enter the Release year of the book:',
    STACK:'Enter the stack id:',
    AUTHORS:'Enter the name of the authors of the book:',
    PUBLISHER:'Enter the Publisher Name of the book:',
    CHOOSE_CAT:'Choose the Category',
    EDITION:'Enter the edition of the book:',
    ADD:'Add',
    DELETE:'Delete',
    EDIT :'Edit',
    DISABLE:'Disable',
    ENABLE:'Enable',
    BOOK:'Book',
    CATEGORY:'Category',
    USER:'User',
    EX_USER:'Executive User',
    BOOK_CREATE_SUCCESS:'Successfully created the book',
    BOOK_CREATE_FAILURE:'Book not created',
    CONFIRM_PASSWORD:'Confirm Password',
    FIRSTNAME:'First Name',
    LASTNAME:'Last Name',
    REQUIRED_CPASSWORD:'Please confirm the Password',
    FIRST_REQUIRED:'First Name Required',
    PASS_MATCH:'Password Does Not Match',
    ADD_EX_SUCCESS:'Successfully added the executive user',
    EMAIL_EXIST:'Email Id Already exist',
    CAT_CREATE:'Create Category',
    CATEGORY_NAME:'Category Name',
    CREATE_EX :'Add Executive',
    ADD_CAT_SUCCESS:'Category added Successfully',
    ADD_CAT_EXIST:'Category Already exist',
    REQUIRED_CATEGORY:'Category Name is required',
    CREATE_EX :'Create Executive User'


}
